### ISSUE TITLE
LoadConfig function overwritten existing config.ini 

### ISSUE THREAD

**Issue by pgalonza** [cy33hc/switch-ezremote-client#15]
Hello, I put own config.ini in to switch/ezremote-client folder, and after starting application config content was overwintered from template.

**Comment by cy33hc** [comment]
@pgalonza You should not change the overall structure of the config.ini, just change the values only. Also things are case sensitive. The app might be only supporting Unix style linefeed, so if you use Windows Notepad to edit, it might be a problem. Use [Notepad++](https://notepad-plus-plus.org/) instead and make sure to save in Unix (LF).

**Comment by pgalonza** [comment]
@cy33hc Thenk Yes, I changed the structure by removing some of the template blocks. Thanks for the app.
