### ISSUE TITLE
 Ukrainian translation

### ISSUE THREAD

**Issue by skylegend509** [cy33hc/switch-ezremote-client#3]
I've done a Ukrainian translation
[Ukrainian.txt](https://github.com/cy33hc/switch-ezremote-client/files/13994304/Ukrainian.txt)

**Comment by cy33hc** [comment]
@skylegend509 Thx

**Comment by cy33hc** [comment]
@skylegend509 This has been included in release 1.0.2 https://github.com/cy33hc/switch-ezremote-client/releases/tag/1.02
