### ISSUE TITLE
Simplified Chinese Translation 1.0.1

### ISSUE THREAD

**Issue by kavid** [cy33hc/switch-ezremote-client#4]
Simplified Chinese Translation 1.0.1
[Simplified Chinese.zip](https://github.com/cy33hc/switch-ezremote-client/files/15138349/Simplified.Chinese.zip)

**Comment by cy33hc** [comment]
@kavid Thx

**Comment by cy33hc** [comment]
@kavid This has been include in new release 1.0.2. https://github.com/cy33hc/switch-ezremote-client/releases/tag/1.02
