### ISSUE TITLE
crashing with smb

### ISSUE THREAD

**Issue by erichegit** [cy33hc/switch-ezremote-client#6]
I configured an smb:// mount with username and password and it crashes that I only can reboot (Power) or boot into hekate (Vol).
Is there an exception handling or a logfile that I can check to understand why this is happening?

**Comment by cy33hc** [comment]
@erichegit You URL is probably invalid. It has to follow the following rules. See highlights, the required fields.

smb://hostname[:port]/sharename

  - hostname can be the textual hostname or an IP address. hostname is **required**
  - port is optional and defaults to 445 if not provided
  - s**harename is required**

**Comment by cy33hc** [comment]
Fixed crash cause by invalid smb url in release 1.03
