### ISSUE TITLE
Failed complie due to `HTTPClient`

### ISSUE THREAD

**Issue by dragonflylee** [cy33hc/switch-ezremote-client#9]
I try to compile under docker `devkitpro/devkita64` with extern depency https://github.com/embeddedmz/httpclient-cpp

but `CHTTPClient::EncodeUrl` was missing in https://github.com/embeddedmz/httpclient-cpp/blob/master/HTTP/HTTPClient.h

**Comment by cy33hc** [comment]
I had customized httpclient-cpp. I haven't pushed the fork to git

**Comment by cy33hc** [comment]
@dragonflylee Use my fork of the httpclient-cpp.  https://github.com/cy33hc/httpclient-cpp
